output_dir: ./runs/t1000_base4_b16_lr1e3_lrm60_85
dataset:
  labelled_root: ./data
  time_bin_us: 1000
model:
  out_channels: 1
  base_channels: 4
  use_batch_norm: true
train:
  batch_size: 16
  num_workers: 8
  epochs: 100
  lr: 0.001
  lr_milestones:
  - 60
  - 85
